//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInfo
    {
        public long CourseInfoId { get; set; }
        public long CourseId { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }
        public string FolderLocation { get; set; }
        public string LaunchFileName { get; set; }
        public Nullable<long> FileSizeInKB { get; set; }
        public string ScoLabel { get; set; }
        public Nullable<bool> IsFinalized { get; set; }
        public Nullable<int> WindowWidth { get; set; }
        public Nullable<int> WindowHeight { get; set; }
        public Nullable<int> PassMarks { get; set; }
        public Nullable<bool> IsUserDefined { get; set; }
        public int LanguageId { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public Nullable<long> LastModifiedById { get; set; }
        public long CreatedById { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Course Course { get; set; }
    }
}
